#include <YSI_Coding\y_hooks>
#include "iorp-system/world/actor-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/area-69-player-location-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/camera-interpolate-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/camp-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/corpses-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/dynamic-object-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/entrance-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/gate-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/house-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/ls-elevator-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/map-icon-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/millennium-mountain-lift-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/teleport-with-map.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/timezone-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/information-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/brothel-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/static-vehicle-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/easter-egg.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/fridge-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/gym-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/hit-market-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/hotel.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/iorp-birthday.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/nuclear-launch-site.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/random-message-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/world/space-station.pwn"

#include "iorp-system/world/trailer/index.pwn"