#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/shipments/resources-shipment.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/shipments/electrical-shipment.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/shipments/medical-shipment.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/shipments/firework-shipment.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/shipments/cloth-shipment.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/shipments/sex-toy-shop.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/shipments/weapon-shipment.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/shipments/clothes-accessories.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/shipments/light-motor-dealership.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/shipments/heavy-motor-dealership.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/shipments/two-wheeler-dealership.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/shipments/helicopter-dealership.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/shipments/plane-dealership.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/shipments/boat-dealership.pwn"