#include <YSI_Coding\y_hooks>
#include "iorp-system/minigame/system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/minigame/casino-machine.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/minigame/derby.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/minigame/football-game-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/minigame/lottery-minigame-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/minigame/mine-sweeper-game.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/minigame/pong-minigame.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/minigame/race-system-v2.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/minigame/snake-minigame-v2.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/minigame/tic-tac-toe-minigame.pwn"