#include <YSI_Coding\y_hooks>
#include "iorp-system/crime/ammunation-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/crime/attach-weapon-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/crime/bank-robbery.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/crime/cops-extended-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/crime/drop-gun-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/crime/drug-system-v2.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/crime/give-weapon-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/crime/register-hacking-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/crime/safe-hacking-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/crime/taser-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/crime/wanted-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/crime/weapon-save-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/crime/missile-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/crime/heist-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/crime/death-medic-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/crime/medic-operation-systems.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/crime/lspd-self-jail.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/crime/mafia-zone-capture.pwn"