#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/bank-system-v2.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/food-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/fuel-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/reward-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/shop-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/vault-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/dealership-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/advertisement-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/bitcoin-items.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/bitcoin-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/debt-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/refund-system.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/reward-cash-price.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/economy/dynamic-shop-system.pwn"

#include "iorp-system/economy/dynamic-shops/index.pwn"
#include "iorp-system/economy/factories/index.pwn"
#include "iorp-system/economy/material-shipment/index.pwn"
#include "iorp-system/economy/shipments/index.pwn"
#include "iorp-system/economy/shop/index.pwn"