#include <YSI_Coding\y_hooks>
#include "iorp-system/events/stunt-world/index.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/events/skyfall/index.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/events/css/event.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/events/race-track/index.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/events/cod/event.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/events/pubg/index.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/events/fallout/index.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/events/sumo/index.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/events/system.pwn"