#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/amusement-park-sf.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/angel-pine-respawn.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/area-51.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/bank-exterior.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/bank-interior.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/cityhall-exterior.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/cityhall-interior.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/hotel-ls-airport.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/interglobal-television.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/liner-ls-ship.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/ls-beach-house.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/ls-dealership.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/ls-ferris-wheel.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/ls-snackbar.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/lspd-exterior.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/lspd-prison-interior.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/motorcycle-shop-ls.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/presidential-department-hq-interior.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/recruitment-agency.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/restored-hotel-sf.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/skybar-ls.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/toll-sa.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/tuning-ls-airport.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/wood-clothes-shop-ls.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/pharmacy.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/ls-hospital.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/bar1-map.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/bar2-map.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/bar3-map.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/skypiea-stunt-map.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/stunt-evolution.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/race-track.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/disco-bar-ls.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/silver-peak.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/hellzo-dm.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/funfair-ls.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/cs-dust2.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/modern-apartment.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/recording-studio.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/chinatown-garage.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/spawn-interior.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/vinewood-house.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/sf-church.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/supersport69.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/sf-cave-island.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/selection-room.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/skyscraper-ls.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/mulholland.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/bmx-ls-hospital.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/ghetto-patrol-station.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/circuit-race-track.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/ls-bank.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/mention.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/summer-island.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/mining-village.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/fort-map.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/recycling-facility-map.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/underwater-castle.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/desert-village.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/mechanic-garage.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/swimming-pool.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/chinese-headquarter.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/abandoned-city.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/risq-recording-studio.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/bunker-house.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/valkyrie-admin-base.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/samsung-shop-ls.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/screwthis-shop.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/work-shop.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/distro.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/apartment-hotel-room.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/remove-building-only.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/zn-city.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/dino/ls-house.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/dino/college.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/dino/hotel.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/dino/hospital-ext.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/dino/army-camp.pwn"
#include <YSI_Coding\y_hooks>
#include "iorp-system/maps/dino/sumo.pwn"
#include "iorp-system/maps/priyanshu/index.pwn"