new const SkiNames[312][] = {
    "Carl Johnson",
    "The Truth",
    "Maccer",
    "Andre",
    "Big Bear Thorne [Thin]",
    "Big Bear Thorne [Big]",
    "Emmet",
    "Taxi Driver/Train Driver",
    "Janitor",
    "Normal Ped",
    "Old Woman",
    "Casino croupier",
    "Rich Woman",
    "Street Girl",
    "Normal Ped",
    "Mr.Whittaker (RS Haul Owner)",
    "Airport Ground Worker",
    "Businessman",
    "Beach Visitor",
    "DJ",
    "Rich Guy (Madd Dogg's Manager)",
    "Normal Ped",
    "Normal Ped",
    "BMXer",
    "Madd Dogg Bodyguard",
    "Madd Dogg Bodyguard",
    "Backpacker",
    "Construction Worker",
    "Drug Dealer",
    "Drug Dealer",
    "Drug Dealer",
    "Farm-Town inhabitant",
    "Farm-Town inhabitant",
    "Farm-Town inhabitant",
    "Farm-Town inhabitant",
    "Gardener",
    "Golfer",
    "Golfer",
    "Normal Ped",
    "Normal Ped",
    "Normal Ped",
    "Normal Ped",
    "Jethro",
    "Normal Ped",
    "Normal Ped",
    "Beach Visitor",
    "Normal Ped",
    "Normal Ped",
    "Normal Ped",
    "Snakehead (Da Nang)",
    "Mechanic",
    "Mountain Biker",
    "Mountain Biker",
    "Unknown",
    "Normal Ped",
    "Normal Ped",
    "Normal Ped",
    "Oriental Ped",
    "Oriental Ped",
    "Normal Ped",
    "Normal Ped",
    "Pilot",
    "Colonel Fuhrberger",
    "Prostitute",
    "Prostitute",
    "Kendl Johnson",
    "Pool Player",
    "Pool Player",
    "Priest/Preacher",
    "Normal Ped",
    "Scientist",
    "Security Guard",
    "Hippy",
    "Hippy",
    "-",
    "Prostitute",
    "Stewardess",
    "Homeless",
    "Homeless",
    "Homeless",
    "Boxer",
    "Boxer",
    "Black Elvis",
    "White Elvis",
    "Blue Elvis",
    "Prostitute",
    "Ryder with robbery mask",
    "Stripper",
    "Normal Ped",
    "Normal Ped",
    "Jogger",
    "Rich Woman",
    "Rollerskater",
    "Normal Ped",
    "Normal Ped",
    "Normal Ped",
    "Jogger",
    "Lifeguard",
    "Normal Ped",
    "Rollerskater",
    "Biker",
    "Normal Ped",
    "Balla",
    "Balla",
    "Balla",
    "Grove Street Families",
    "Grove Street Families",
    "Grove Street Families",
    "Los Santos Vagos",
    "Los Santos Vagos",
    "Los Santos Vagos",
    "The Russian Mafia",
    "The Russian Mafia",
    "The Russian Mafia",
    "Varios Los Aztecas",
    "Varios Los Aztecas",
    "Varios Los Aztecas",
    "Triad",
    "Triad",
    "Johhny Sindacco",
    "Triad Boss",
    "Da Nang Boy",
    "Da Nang Boy",
    "Da Nang Boy",
    "The Mafia",
    "The Mafia",
    "The Mafia",
    "The Mafia",
    "Farm Inhabitant",
    "Farm Inhabitant",
    "Farm Inhabitant",
    "Farm Inhabitant",
    "Farm Inhabitant",
    "Farm Inhabitant",
    "Homeless",
    "Homeless",
    "Normal Ped",
    "Homeless",
    "Beach Visitor",
    "Beach Visitor",
    "Beach Visitor",
    "Businesswoman",
    "Taxi Driver",
    "Crack Maker",
    "Crack Maker",
    "Crack Maker",
    "Crack Maker",
    "Businessman",
    "Businesswoman",
    "Big Smoke Armored",
    "Businesswoman",
    "Normal Ped",
    "Prostitute",
    "Construction Worker",
    "Beach Visitor",
    "Well Stacked Pizza Worker",
    "Barber",
    "Hillbilly",
    "Farmer",
    "Hillbilly",
    "Hillbilly",
    "Farmer",
    "Hillbilly",
    "Black Bouncer",
    "White Bouncer",
    "White MIB agent",
    "Black MIB agent",
    "Cluckin' Bell Worker",
    "Hotdog/Chilli Dog Vendor",
    "Normal Ped",
    "Normal Ped",
    "Blackjack Dealer",
    "Casino croupier",
    "San Fierro Rifa",
    "San Fierro Rifa",
    "San Fierro Rifa",
    "Barber",
    "Barber",
    "Whore",
    "Ammunation Salesman",
    "Tattoo Artist",
    "Punk",
    "Cab Driver",
    "Normal Ped",
    "Normal Ped",
    "Normal Ped",
    "Normal Ped",
    "Businessman",
    "Normal Ped",
    "Valet",
    "Barbara Schternvart",
    "Helena Wankstein",
    "Michelle Cannes",
    "Katie Zhan",
    "Millie Perkins",
    "Denise Robinson",
    "Farm-Town inhabitant",
    "Hillbilly",
    "Farm-Town inhabitant",
    "Farm-Town inhabitant",
    "Hillbilly",
    "Farmer",
    "Farmer",
    "Karate Teacher",
    "Karate Teacher",
    "Burger Shot Cashier",
    "Cab Driver",
    "Prostitute",
    "Su Xi Mu (Suzie)",
    "Oriental Noodle stand vendor",
    "Oriental Boating School Instructor",
    "Clothes shop staff",
    "Homeless",
    "Weird old man",
    "Waitress (Maria Latore)",
    "Normal Ped",
    "Normal Ped",
    "Clothes shop staff",
    "Normal Ped",
    "Rich Woman",
    "Cab Driver",
    "Normal Ped",
    "Normal Ped",
    "Normal Ped",
    "Normal Ped",
    "Normal Ped",
    "Normal Ped",
    "Oriental Businessman",
    "Oriental Ped",
    "Oriental Ped",
    "Homeless",
    "Normal Ped",
    "Normal Ped",
    "Normal Ped",
    "Cab Driver",
    "Normal Ped",
    "Normal Ped",
    "Prostitute",
    "Prostitute",
    "Homeless",
    "The D.A",
    "Afro-American",
    "Mexican",
    "Prostitute",
    "Stripper",
    "Prostitute",
    "Stripper",
    "Biker",
    "Biker",
    "Pimp",
    "Normal Ped",
    "Lifeguard",
    "Naked Valet",
    "Bus Driver",
    "Biker Drug Dealer",
    "Chauffeur (Limo Driver)",
    "Stripper",
    "Stripper",
    "Heckler",
    "Heckler",
    "Construction Worker",
    "Cab driver",
    "Cab driver",
    "Normal Ped",
    "Clown (Ice-cream Van Driver)",
    "Officer Frank Tenpenny (Corrupt Cop)",
    "Officer Eddie Pulaski (Corrupt Cop)",
    "Officer Jimmy Hernandez",
    "Dwaine/Dwayne",
    "Melvin Big Smoke Harris (Mission)",
    "Sean 'Sweet' Johnson",
    "Lance 'Ryder' Wilson",
    "Mafia Boss",
    "T-Bone Mendez",
    "Paramedic (Emergency Medical Technician)",
    "Paramedic (Emergency Medical Technician)",
    "Paramedic (Emergency Medical Technician)",
    "Firefighter",
    "Firefighter",
    "Firefighter",
    "Los Santos Police Officer",
    "San Fierro Police Officer",
    "Las Venturas Police Officer",
    "County Sheriff",
    "LSPD Motorbike Cop",
    "S.W.A.T Special Forces",
    "FBI Agent",
    "San Andreas Army Soldier",
    "Desert Sheriff",
    "Zero",
    "Ken Rosenberg",
    "Kent Paul",
    "Cesar Vialpando",
    "Jeffery OG Loc Martin/Cross",
    "Wu Zi Mu (Woozie)",
    "Michael Toreno (Mike)",
    "Jizzy B.",
    "Madd Dogg",
    "Catalina",
    "Claude Speed",
    "Los Santos Police Officer (Without gun holster)",
    "San Fierro Police Officer (Without gun holster)",
    "Las Venturas Police Officer (Without gun holster)",
    "Los Santos Police Officer (Without uniform)",
    "Los Santos Police Officer (Without uniform)",
    "Las Venturas Police Officer (Without uniform)",
    "Los Santos Police Officer",
    "San Fierro Police Officer",
    "San Fierro Paramedic (Emergency Medical Technician)",
    "Las Venturas Police Officer",
    "Country Sheriff (Without hat)",
    "Desert Sheriff (Without hat)"
};

stock GetSkinName(skinid) {
    new string[50];
    if(skinid < 0 || skinid > 311) return string;
    format(string, sizeof string, "%s", SkiNames[skinid]);
    return string;
}